### ISSUE TITLE
Bug: Item Level displayed on icon is incorrect

### ISSUE THREAD

**Issue by khay85** [cogwerkz/Bagnon_ItemLevel#10]
When I look at the icons, it shows the numbers, but they are sometimes incorrect. Mousing over the item, in the tooltip the item level is different than the one displayed.

Like this one, 5th row 1st column on left. Shows 769, but is actually 719.
![wrongilvl](https://user-images.githubusercontent.com/24641707/33240569-6ac28c80-d27d-11e7-955a-fe8a2b0b9d4c.png)

**Comment by Anderzenn** [comment]
I can confirm that this is also an issue with heirlooms if they're not upgraded.
When they hit 60 (if not upgraded at all) they stop leveling up and their ilvl stops increasing as well but the addon shows the ilvl as if they were upgraded.

**Comment by goldpaw** [comment]
fixed in 1.0.9
