### ISSUE TITLE
Artifact Weapon iLvl 

### ISSUE THREAD

**Issue by Skidadle** [cogwerkz/Bagnon_ItemLevel#11]
The item level on the artifact weapons are wrong. 
Wondering if i missed something but thought id post it here.

![wrong item level bagnon](https://user-images.githubusercontent.com/31952271/33334239-7a76dcce-d469-11e7-8b19-0d5dfb300896.png)

**Comment by Anderzenn** [comment]
Just want to point out that #10 reports that it has some issues with (my guess) legion items :P (just helping out Cogwerkz since it must be bothersome to have multiple reports of the same thing)

**Comment by Skidadle** [comment]
My bad, overlooked that post.
I ussually disenchant or sell the green items without paying attention to them.

**Comment by goldpaw** [comment]
fixed in 1.0.9
