### ISSUE TITLE
Nether Crucible's extra 15 weapon ilvls are not counted.

### ISSUE THREAD

**Issue by Nillx** [cogwerkz/Bagnon_ItemLevel#12]
Noticed that the 15 extra ilvls from the Nether Crucible are not counted towards the weapon ilvl. Its showing the base weapon ilvl.

**Comment by goldpaw** [comment]
Yeah, the extra item levels from the new'ish artifact relic traits aren't included yet. Working on a fix!

**Comment by goldpaw** [comment]
fixed in 1.0.9
