### ISSUE TITLE
Update to Bagnon

### ISSUE THREAD

**Issue by Comicus** [cogwerkz/Bagnon_ItemLevel#13]
it appears the author has started beta version that may have conflicts with your addon:

5x Bagnon_ItemLevel\main.lua:84: attempt to call method 'GetItem' (a nil value)
Bagnon_ItemLevel\main.lua:84: in function <Bagnon_ItemLevel\main.lua:83>
[C]: in function `Update'
Bagnon\external\Wildpants\components\item.lua:127: in function <Bagnon\external\Wildpants\components\item.lua:122>
[C]: in function `Show'
Bagnon\external\Wildpants\components\item.lua:30: in function `New'
...s\Bagnon\external\Wildpants\components\itemFrame.lua:119: in function <...s\Bagnon\external\Wildpants\components\itemFrame.lua:108>

Locals:
self = ContainerFrame1Item1 {
 timeSinceUpgradeCheck = 0
 bag = 0
 BattlepayItemTexture = <unnamed> {
 }
 Border = <unnamed> {
 }
 flash = <unnamed> {
 }
 scheduledSecondaryUpdate = true
 IconBorder = <unnamed> {
 }
 newitemglowAnim = <unnamed> {
 }
 hasItem = "|cffffffff|Hitem:116119::::::::106:269::::::|h[Ango'rosh Sorcerer Stone]|h|r"
 icon = ContainerFrame1Item1IconTexture {
 }
 JunkIcon = <unnamed> {
 }
 count = 4
 info = <table> {
 }
 Count = ContainerFrame1Item1Count {
 }
 frame = BagnonFrameinventory {
 }
 NewItemTexture = <unnamed> {
 }
 QuestBorder = ContainerFrame1Item1IconQuestTexture {
 }
 0 = <userdata>
 readable = false
 UpgradeIcon = <unnamed> {
 }
 Flash = <unnamed> {
 }
 flashAnim = <unnamed> {
 }
 searchOverlay = ContainerFrame1Item1SearchOverlay {
 }
 Cooldown = ContainerFrame1Item1Cooldown {
 }
 SplitStack = <function> defined @FrameXML\ContainerFrame.lua:918
}
(*temporary) = nil
(*temporary) = ContainerFrame1Item1 {
 timeSinceUpgradeCheck = 0
 bag = 0
 BattlepayItemTexture = <unnamed> {
 }
 Border = <unnamed> {
 }
 flash = <unnamed> {
 }
 scheduledSecondaryUpdate = true
 IconBorder = <unnamed> {
 }
 newitemglowAnim = <unnamed> {
 }
 hasItem = "|cffffffff|Hitem:116119::::::::106:269::::::|h[Ango'rosh Sorcerer Stone]|h|r"
 icon = ContainerFrame1Item1IconTexture {
 }
 JunkIcon = <unnamed> {
 }
 count = 4
 info = <table> {
 }
 Count = ContainerFrame1Item1Count {
 }
 frame = BagnonFrameinventory {
 }
 NewItemTexture = <unnamed> {
 }
 QuestBorder = ContainerFrame1Item1IconQuestTexture {
 }
 0 = <userdata>
 readable = false
 UpgradeIcon = <unnamed> {
 }
 Flash = <unnamed> {
 }
 flashAnim = <unnamed> {
 }
 searchOverlay = ContainerFrame1Item1SearchOverlay {
 }
 Cooldown = ContainerFrame1Item1Cooldown {
 }
 SplitStack = <function> defined @FrameXML\ContainerFrame.lua:918
}
(*temporary) = "attempt to call method 'GetItem' (a nil value)"
cache = <table> {
}
initButton = <function> defined @Bagnon_ItemLevel\main.lua:55
GetItemInfo = <function> defined =[C]:-1
GetDetailedItemLevelInfo = <function> defined =[C]:-1
tonumber = <function> defined =[C]:-1
string_match = <function> defined =[C]:-1
_G = <table> {
 ContainerFrame5Item7 = ContainerFrame5Item7 {
 }
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 ARL_DatamineCopyFrame = ARL_DatamineCopyFrame {
 }
 SetTrainerServiceTypeFilter = <function> defined =[C]:-1
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 734
 EventTraceFrameButton7HideButton = EventTraceFrameButton7HideButton {
 }
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 394
 BT4Button58 = BT4Button58 {
 }
 CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture = CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture {
 }
 BtWQuests_UpdateChain = <function> defined @BtWQuests\BtWQuests.lua:1225
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 InterfaceOptionsNamesPanelUnitNameplatesShowAll = InterfaceOptionsNamesPanelUnitNameplatesShowAll {
 }
 LibDugi_UIDropDownMenu_SetSelectedValue = <function> defined @DugisGuideViewerZ\Libs\DropDownMenu\UIDropDownMenu.lua:733
 LFGListInviteDialog_OnEvent = <function> defined @FrameXML\LFGList.lua:2377
 MerchantItem6AltCurrencyFrameItem1Text = MerchantItem6AltCurrencyFrameItem1Text {
 }
 BINDING_NAME_NAMEPLATES = "Show Enemy Name Plates"
 CHAT_HEADER_SUFFIX = ": "
 MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
 }
 IsReferAFriendLinked = <function> defined =[C]:-1
 Overachiever_SearchFrameContainerButton1TabardBackground = Overachiever_SearchFrameContainerButton1TabardBackground {
 }
 AudioOptionsVoicePanelMicrophoneVolumeThumb = AudioOptionsVoicePanelMicrophoneVolumeThumb {
 }
 PaperDollTitlesPaneButton14BgTop = PaperDollTitlesPaneButton14BgTop {
 }
 CALENDAR_RAID_RESET_DESCRIPTI

**Comment by goldpaw** [comment]
Jaliborc added back :GetItem(), so this works as intended again in the most recent betas.
