### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by SethAluma** [cogwerkz/Bagnon_ItemLevel#2]
Error:
`84x Bagnon_ItemLevel\main.lua:44: attempt to call upvalue 'string_match' (a nil value)
Bagnon_ItemLevel\main.lua:44: in function <Bagnon_ItemLevel\main.lua:21>
[C]: in function `Update'
Bagnon\external\Wildpants\components\item.lua:126: in function <Bagnon\external\Wildpants\components\item.lua:121>
[C]: in function `Show'
Bagnon\external\Wildpants\components\item.lua:29: in function `New'
...s\Bagnon\external\Wildpants\components\itemFrame.lua:120: in function <...s\Bagnon\external\Wildpants\components\itemFrame.lua:109>

Locals:
self = ContainerFrame1Item1 {
 timeSinceUpgradeCheck = 0
 CanIMogItOverlay = CIMIOverlayFrame_ContainerFrame1Item1 {
 }
 BattlepayItemTexture = <unnamed> {
 }
 Border = <unnamed> {
 }
 flash = <unnamed> {
 }
 scheduledSecondaryUpdate = true
 IconBorder = <unnamed> {
 }
 newitemglowAnim = <unnamed> {
 }
 hasItem = "|cffe6cc80|Hitem:128942::137549:151498:137377::::110:267:16777472:9:1:747:318:1:3:3415:1532:3528:3:3567:1672:3528:3:3418:1542:3528|h[Ulthalesh, the Deadwind Harvester]|h|r"
 icon = ContainerFrame1Item1IconTexture {
 }
 JunkIcon = <unnamed> {
 }
 Flash = <unnamed> {
 }
 count = 1
 frame = BagnonFrameinventory {
 }
 bag = 0
 NewItemTexture = <unnamed> {
 }
 QuestBorder = ContainerFrame1Item1IconQuestTexture {
 }
 0 = <userdata>
 readable = false
 UpgradeIcon = <unnamed> {
 }
 Count = ContainerFrame1Item1Count {
 }
 flashAnim = <unnamed> {
 }
 searchOverlay = ContainerFrame1Item1SearchOverlay {
 }
 Cooldown = ContainerFrame1Item1Cooldown {
 }
 SplitStack = <function> defined @FrameXML\ContainerFrame.lua:918
}
itemLink = "|cffe6cc80|Hitem:128942::137549:151498:137377::::110:267:16777472:9:1:747:318:1:3:3415:1532:3528:3:3567:1672:3528:3:3418:1542:3528|h[Ulthalesh, the Deadwind Harvester]|h|r"
_ = "Ulthalesh, the Deadwind Harvester"
_ = "|cffe6cc80|Hitem:128942::137549:151498:137377::::110:267:16777472:9:1:747:318:1:3:3415:1532:3528:3:3567:1672:3528:3:3418:1542:3528|h[Ulthalesh, the Deadwind Harvester]|h|r"
itemRarity = 6
iLevel = 750
_ = 0
_ = "Weapon"
_ = "Staves"
_ = 1
itemEquipLoc = "INVTYPE_2HWEAPON"
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = "|cffe6cc80|Hitem:128942::137549:151498:137377::::110:267:16777472:9:1:747:318:1:3:3415:1532:3528:3:3567:1672:3528:3:3418:1542:3528|h[Ulthalesh, the Deadwind Harvester]|h|r"
(*temporary) = "item:(%d+)"
(*temporary) = "attempt to call upvalue 'string_match' (a nil value)"
cache = <table> {
 (null) = <unnamed> {
 }
}
CreateFrame = <function> defined =[C]:-1
_G = <table> {
 ContainerFrame5Item7 = ContainerFrame5Item7 {
 }
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 SetTrainerServiceTypeFilter = <function> defined =[C]:-1
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 734
 EventTraceFrameButton7HideButton = EventTraceFrameButton7HideButton {
 }
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 394
 CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture = CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture {
 }
 InspectFrameTab1HighlightTexture = InspectFrameTab1HighlightTexture {
 }
 PawnItemComparer = <function> defined @Pawn\Pawn.lua:3427
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 LibDugi_UIDropDownMenu_SetSelectedValue = <function> defined @DugisGuideViewerZ\Libs\DropDownMenu\UIDropDownMenu.lua:733
 LFGListInviteDialog_OnEvent = <function> defined @FrameXML\LFGList.lua:2377
 MerchantItem3AltCurrencyFrameItem1Text = MerchantItem3AltCurrencyFrameItem1Text {
 }
 BINDING_NAME_NAMEPLATES = "Show Enemy Name Plates"
 CHAT_HEADER_SUFFIX = ": "
 EncounterDetails_SpellAurasScrollScrollChildFrame = EncounterDetails_SpellAurasScrollScrollChildFrame {
 }
 MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
 }
 IsReferAFriendLinked = <function> defined =[C]:-1
 AudioOptionsVoicePanelMicrophoneVolumeThumb = AudioOptionsVoicePanelMicrophoneVolumeThumb {
 }
 PaperDollTitlesPaneButton14BgTop = PaperDollTitlesPaneButton14BgTop {
 }
 InspectModelFrameControlFrameZoomInButtonBg = InspectModelFrameControlFrameZoomInButtonBg {
 }
 CALENDAR_RAID_RESET_DESCRIPTION = "%1$s resets at %2$s."
 CalendarTodayTexture = CalendarTodayTexture {
 }
 HasZoneAbility = <function> defined @FrameXML\ZoneAbility.lua:152
 MoneyFrame_OnEvent = <function> defined @FrameXML\MoneyFrame.lua:221
 LE_GAME`

**Comment by goldpaw** [comment]
Already fixed in the latest version here on GitHub, waiting for Curse to let it through on their end.
