### ISSUE TITLE
Problem with german client

### ISSUE THREAD

**Issue by Forrest-rco** [cogwerkz/Bagnon_ItemLevel#4]
Hello,

i don't see ilvl on items on the german client.

**Comment by Forrest-rco** [comment]
i have rename the dir to "Bagnon_ItemLevel" and all is now fine !

**Comment by goldpaw** [comment]
Ah, yes. I should probably make a note about that, to rename the folder when downloading from GitHub. 

It's usually up to date on Curse, though. It's pushed automatically from GitHub to Curse/Twitch every time I upload something. :)
