### ISSUE TITLE
Suggestion: ilvl for all items?

### ISSUE THREAD

**Issue by C-M0N** [cogwerkz/Bagnon_ItemLevel#9]
Hey,
in the old SyLevel it was possible to see the ilvl of all items not only gear.

How can i see the ilvl of ALL items? 
What lines must i change in the code?

thx :)

**Comment by goldpaw** [comment]
Wouldn't make very much sense, except maybe for some gems. The idea of an item level is to measure quality, so the item levels of hearthstones, enchanter rods, fish and so on are just spam. 

I've changed the addon to also show the item level of white quality equipable gear, though. Like early starter zone vendor gear, beginner fishing poles, etc.
